on: push
name: Publish on Netlify

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run : sudo apt-get update -y && sudo apt-get install asciidoctor -y
    - run: make dist

    - name: Publish
      uses: netlify/actions/cli@master
      with:
        args: deploy --prod --dir=./dist/
      env:
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}